version: '3.3'
services:
  openethereum:
    image: openethereum/openethereum:v3.1.0
    volumes:
      - "./openethereum/:/home/openethereum/.local/share/openethereum/"
    command:
      - "--base-path"
      - "/home/openethereum/.local/share/openethereum"
      - "--config"
      - "/home/openethereum/.local/share/openethereum/config.toml"
      - "--no-warp"
    user: root
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
      - "9091:9091"
      - "9092:9092"
